apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: dfras
  labels:
    app: ml-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: dfras-infrastructure-ml-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8007
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "dfras_user"
        - name: POSTGRES_PASSWORD
          value: "dfras_password"
        - name: POSTGRES_DB
          value: "dfras_db"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: dfras
  labels:
    app: ml-service
spec:
  selector:
    app: ml-service
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
  type: ClusterIP
